INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Advertising 1", "Advertising", 1000000, "03/12/19", "10/12/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Advertising 2", "Advertising", 150000, "04/12/19", "07/12/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Consulting 1", "Consulting", 13500100, "11/12/19", "03/12/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Technology 1", "Technology", 30002000, "12/12/19", "10/12/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Government 1", "Government", 200000, "01/01/19", "09/06/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Government 2", "Government", 500000, "02/02/19", "11/11/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Government 3", "Government", 750500, "03/04/19", "12/12/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Banking 1", "Banking", 6000000000, "06/12/19", "10/12/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Consulting 1", "Consulting", 600000, "05/01/19", "10/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("IT 1", "IT", 840000, "03/12/19", "10/12/19");

INSERT INTO users (name, age) VALUES ("Shad Ortiz" , 29);
INSERT INTO users (name, age) VALUES ("Matthew Schimmel DVM" , 31);
INSERT INTO users (name, age) VALUES ("Lawanda Lebsack Ortiz" , 21);
INSERT INTO users (name, age) VALUES ("Robby Daugherty" , 45);
INSERT INTO users (name, age) VALUES ("Dania Dicki" , 54);
INSERT INTO users (name, age) VALUES ("Wilton Monahan" , 38);
INSERT INTO users (name, age) VALUES ("Brendon Willms" , 33);
INSERT INTO users (name, age) VALUES ("Milan Schmidt I" , 30);
INSERT INTO users (name, age) VALUES ("Armando Moore" , 18);
INSERT INTO users (name, age) VALUES ("Tamra Douglas" , 19);
INSERT INTO users (name, age) VALUES ("Manual McDermott" , 20);
INSERT INTO users (name, age) VALUES ("Danny Lynch" , 24);
INSERT INTO users (name, age) VALUES ("Joe Spinka" , 46);
INSERT INTO users (name, age) VALUES ("Elroy Maggio" , 35);
INSERT INTO users (name, age) VALUES ("Florentino Streich" , 25);
INSERT INTO users (name, age) VALUES ("Guillermo Kulas" , 34);
INSERT INTO users (name, age) VALUES ("Andrea Robel" , 46);
INSERT INTO users (name, age) VALUES ("Jeffery Kautzer" , 35);
INSERT INTO users (name, age) VALUES ("Dusty Blick" , 25);
INSERT INTO users (name, age) VALUES ("Alexia Fritsch" , 15);

INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 3, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1500, 10, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (300, 6, 18);
INSERT INTO pledges (amount, project_id, user_id) VALUES (20, 9, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (3000, 6, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 5, 8);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 4, 8);
INSERT INTO pledges (amount, project_id, user_id) VALUES (45, 2, 7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (5, 9, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (70, 8, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (900, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 2, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (15, 1, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (16, 4, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 8, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (150, 2, 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (200, 3, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 1, 13);
INSERT INTO pledges (amount, project_id, user_id) VALUES (130, 7, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (30, 6, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (40, 9, 18);
INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 8, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (15, 4, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (80, 3, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (60, 2, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (40, 1, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (25, 7, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (45, 6, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (20, 8, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 10, 6);
